In [1]:
import pandas as pd

In [2]:
eda = pd.read_csv("EDA_df.csv").rename(columns={'data',

In [32]:
eda

             data student       test
0        0.000000      S1      Final
1        0.005125      S1      Final
2        0.020501      S1      Final
3        0.021783      S1      Final
4        0.023064      S1      Final
...           ...     ...        ...
1773115  0.021781     S10  Midterm 2
1773116  0.020500     S10  Midterm 2
1773117  0.020500     S10  Midterm 2
1773118  0.020500     S10  Midterm 2
1773119  0.021781     S10  Midterm 2

[1773120 rows x 3 columns]

In [31]:
pd.concat([eda, hr, temp], axis=1)

,data,student,test,data,student,test,temp (C°),student,test
0,0.000000,S1,Final,116.00,S1,Final,21.89,S1,Final
1,0.005125,S1,Final,82.50,S1,Final,21.89,S1,Final
2,0.020501,S1,Final,96.33,S1,Final,21.89,S1,Final
3,0.021783,S1,Final,86.25,S1,Final,21.89,S1,Final
4,0.023064,S1,Final,98.60,S1,Final,21.89,S1,Final
...,...,...,...,...,...,...,...,...,...
1773115,0.021781,S10,Midterm 2,NaN,NaN,NaN,NaN,NaN,NaN
1773116,0.020500,S10,Midterm 2,NaN,NaN,NaN,NaN,NaN,NaN
1773117,0.020500,S10,Midterm 2,NaN,NaN,NaN,NaN,NaN,NaN
1773118,0.020500,S10,Midterm 2,NaN,NaN,NaN,NaN,NaN,NaN
1773119,0.021781,S10,Midterm 2,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
hr

          data student       test
0       116.00      S1      Final
1        82.50      S1      Final
2        96.33      S1      Final
3        86.25      S1      Final
4        98.60      S1      Final
...        ...     ...        ...
442997  115.07     S10  Midterm 2
442998  116.13     S10  Midterm 2
442999  116.07     S10  Midterm 2
443000  116.47     S10  Midterm 2
443001  116.42     S10  Midterm 2

[443002 rows x 3 columns]

In [25]:
hr = pd.read_csv("HR_df.csv")

In [26]:
hr.groupby('student')['data'].mean()

student
S1     106.573052
S10    106.274096
S2     114.334012
S3     103.301189
S4      98.491765
S5     104.813908
S6     104.821049
S7     103.876402
S8     105.516276
S9      98.872328
Name: data, dtype: float64

In [24]:
eda.groupby('student')['data'].mean()

student
S1     0.160783
S10    0.149010
S2     0.111307
S3     0.271979
S4     0.463462
S5     0.370447
S6     0.256247
S7     0.207661
S8     0.392806
S9     0.298770
Name: data, dtype: float64

In [22]:
grades.set_index("Unnamed: 0").apply('mean', axis=1)

Unnamed: 0
S1     0.836667
S2     0.856667
S3     0.870000
S4     0.753333
S5     0.740000
S6     0.743333
S7     0.506667
S8     0.906667
S9     0.606667
S10    0.703333
dtype: float64

In [6]:
temp = pd.read_csv("TEMP_df.csv")

In [7]:
t1 = temp[temp['test'] == 'Final']

In [9]:
t1.groupby('student')['temp (C°)'].mean()

student
S1     26.184411
S10    26.331471
S2     28.182078
S3     26.509118
S4     28.376879
S5     30.185718
S6     27.047806
S7     25.964929
S8     29.274745
S9     30.808438
Name: temp (C°), dtype: float64

In [10]:
grades = pd.read_csv("grades_df.csv")

In [14]:
grades.set_index("Unnamed: 0").apply('mean', axis=1)

Unnamed: 0
S1     0.836667
S2     0.856667
S3     0.870000
S4     0.753333
S5     0.740000
S6     0.743333
S7     0.506667
S8     0.906667
S9     0.606667
S10    0.703333
dtype: float64